In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit

In [2]:
df = pd.read_csv("housing.csv")

In [3]:
df['income_cat'] = pd.cut(df['median_income'], bins=[0, 1.5, 3.0, 4.5, 6.0, np.inf], labels=[1, 2, 3, 4, 5])

In [4]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(df, df['income_cat']):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [5]:
# Lets remove the income_cat column
for sett in (strat_train_set, strat_test_set):
    sett.drop("income_cat", axis=1, inplace=True)

In [6]:
df = strat_train_set.copy()

In [7]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
12655,-121.46,38.52,29,3873,797.0,2237,706,2.1736,72100,INLAND
15502,-117.23,33.09,7,5320,855.0,2015,768,6.3373,279600,NEAR OCEAN
2908,-119.04,35.37,44,1618,310.0,667,300,2.8750,82700,INLAND
14053,-117.13,32.75,24,1877,519.0,898,483,2.2264,112500,NEAR OCEAN
20496,-118.70,34.28,27,3536,646.0,1837,580,4.4964,238300,<1H OCEAN
...,...,...,...,...,...,...,...,...,...,...
15174,-117.07,33.03,14,6665,1231.0,2026,1001,5.0900,268500,<1H OCEAN
12661,-121.42,38.51,15,7901,1422.0,4769,1418,2.8139,90400,INLAND
19263,-122.72,38.44,48,707,166.0,458,172,3.1797,140400,<1H OCEAN
19140,-122.70,38.31,14,3155,580.0,1208,501,4.1964,258100,<1H OCEAN
19773,-122.14,39.97,27,1079,222.0,625,197,3.1319,62700,INLAND

In [8]:
housing = strat_train_set.drop("median_house_value", axis=1)
housing_labels = strat_train_set["median_house_value"].copy()

In [9]:
from sklearn.impute import SimpleImputer

In [10]:
imputer = SimpleImputer(strategy="median")

In [11]:
housing_num = housing.select_dtypes(include=[np.number])

In [12]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [13]:
X = imputer.transform(housing_num)

In [14]:
X

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [15]:
housing = pd.DataFrame(X, columns=housing_num.columns, index=housing_num.index)

In [16]:
housing['ocean_proximity'] = df['ocean_proximity']

In [17]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
12655,-121.46,38.52,29,3873,797.0,2237,706,2.1736,72100,INLAND
15502,-117.23,33.09,7,5320,855.0,2015,768,6.3373,279600,NEAR OCEAN
2908,-119.04,35.37,44,1618,310.0,667,300,2.8750,82700,INLAND
14053,-117.13,32.75,24,1877,519.0,898,483,2.2264,112500,NEAR OCEAN
20496,-118.70,34.28,27,3536,646.0,1837,580,4.4964,238300,<1H OCEAN
...,...,...,...,...,...,...,...,...,...,...
15174,-117.07,33.03,14,6665,1231.0,2026,1001,5.0900,268500,<1H OCEAN
12661,-121.42,38.51,15,7901,1422.0,4769,1418,2.8139,90400,INLAND
19263,-122.72,38.44,48,707,166.0,458,172,3.1797,140400,<1H OCEAN
19140,-122.70,38.31,14,3155,580.0,1208,501,4.1964,258100,<1H OCEAN
19773,-122.14,39.97,27,1079,222.0,625,197,3.1319,62700,INLAND

# Manish ,Handling missing data

In [18]:
data = pd.read_csv('./housing.csv')

In [19]:
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41,880,129.0,322,126,8.3252,452600,NEAR BAY
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,358500,NEAR BAY
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,352100,NEAR BAY
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,341300,NEAR BAY
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,342200,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,78100,INLAND
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,77100,INLAND
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,92300,INLAND
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,84700,INLAND
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,89400,INLAND

In [20]:
df = data.copy()

In [21]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41,880,129.0,322,126,8.3252,452600,NEAR BAY
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,358500,NEAR BAY
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,352100,NEAR BAY
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,341300,NEAR BAY
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,342200,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,78100,INLAND
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,77100,INLAND
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,92300,INLAND
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,84700,INLAND
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,89400,INLAND

In [22]:
categorical_column = housing.select_dtypes('object')

In [23]:
housing[['ocean_proximity']]

      ocean_proximity
12655          INLAND
15502      NEAR OCEAN
2908           INLAND
14053      NEAR OCEAN
20496       <1H OCEAN
...               ...
15174       <1H OCEAN
12661          INLAND
19263       <1H OCEAN
19140       <1H OCEAN
19773          INLAND

[16512 rows x 1 columns]

In [24]:
# Check Unique values 
set(housing['ocean_proximity'])

{'<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'}

In [25]:
from sklearn.preprocessing import OrdinalEncoder

In [26]:
ordinal = OrdinalEncoder()
ordinal

OrdinalEncoder()

In [27]:
housing_cat = ordinal.fit_transform(housing)

In [28]:
ordinal.categories_

[array([-124.35, -124.3 , -124.27, -124.26, -124.25, -124.23, -124.22,
        -124.21, -124.19, -124.18, -124.17, -124.16, -124.15, -124.14,
        -124.13, -124.11, -124.1 , -124.09, -124.08, -124.07, -124.06,
        -124.05, -124.03, -124.02, -124.  , -123.98, -123.96, -123.92,
        -123.88, -123.85, -123.84, -123.83, -123.82, -123.81, -123.8 ,
        -123.79, -123.78, -123.75, -123.74, -123.73, -123.72, -123.7 ,
        -123.69, -123.68, -123.66, -123.64, -123.63, -123.59, -123.58,
        -123.54, -123.53, -123.52, -123.49, -123.48, -123.47, -123.43,
        -123.41, -123.4 , -123.39, -123.38, -123.37, -123.36, -123.35,
        -123.34, -123.32, -123.28, -123.26, -123.24, -123.23, -123.22,
        -123.21, -123.2 , -123.19, -123.18, -123.17, -123.16, -123.15,
        -123.13, -123.12, -123.11, -123.1 , -123.08, -123.07, -123.04,
        -123.03, -123.02, -123.01, -123.  , -122.97, -122.96, -122.95,
        -122.94, -122.93, -122.92, -122.91, -122.9 , -122.89, -122.88,
        -122.87, -122.86, -122.85, -122.84, -122.83, -122.82, -122.81,
        -122.8 , -122.79, -122.78, -122.77, -122.76, -122.75, -122.74,
        -122.73, -122.72, -122.71, -122.7 , -122.69, -122.68, -122.67,
        -122.66, -122.65, -122.64, -122.63, -122.62, -122.61, -122.6 ,
        -122.59, -122.58, -122.57, -122.56, -122.55, -122.54, -122.53,
        -122.52, -122.51, -122.5 , -122.49, -122.48, -122.47, -122.46,
        -122.45, -122.44, -122.43, -122.42, -122.41, -122.4 , -122.39,
        -122.38, -122.37, -122.36, -122.35, -122.34, -122.33, -122.32,
        -122.31, -122.3 , -122.29, -122.28, -122.27, -122.26, -122.25,
        -122.24, -122.23, -122.22, -122.21, -122.2 , -122.19, -122.18,
        -122.17, -122.16, -122.15, -122.14, -122.13, -122.12, -122.11,
        -122.1 , -122.09, -122.08, -122.07, -122.06, -122.05, -122.04,
        -122.03, -122.02, -122.01, -122.  , -121.99, -121.98, -121.97,
        -121.96, -121.95, -121.94, -121.93, -121.92, -121.91, -121.9 ,
        -121.89, -121.88, -121.87, -121.86, -121.85, -121.84, -121.83,
        -121.82, -121.81, -121.8 , -121.79, -121.78, -121.77, -121.76,
        -121.75, -121.74, -121.73, -121.72, -121.71, -121.7 , -121.69,
        -121.68, -121.67, -121.66, -121.65, -121.64, -121.63, -121.62,
        -121.61, -121.6 , -121.59, -121.58, -121.57, -121.56, -121.55,
        -121.54, -121.53, -121.52, -121.51, -121.5 , -121.49, -121.48,
        -121.47, -121.46, -121.45, -121.44, -121.43, -121.42, -121.41,
        -121.4 , -121.39, -121.38, -121.37, -121.36, -121.35, -121.34,
        -121.33, -121.32, -121.31, -121.3 , -121.29, -121.28, -121.27,
        -121.26, -121.25, -121.24, -121.23, -121.22, -121.21, -121.2 ,
        -121.19, -121.18, -121.17, -121.16, -121.15, -121.14, -121.13,
        -121.12, -121.11, -121.1 , -121.09, -121.08, -121.07, -121.06,
        -121.05, -121.04, -121.03, -121.02, -121.01, -121.  , -120.99,
        -120.98, -120.97, -120.96, -120.95, -120.94, -120.93, -120.92,
        -120.91, -120.9 , -120.89, -120.88, -120.87, -120.86, -120.85,
        -120.84, -120.83, -120.82, -120.81, -120.8 , -120.79, -120.78,
        -120.77, -120.76, -120.75, -120.74, -120.73, -120.72, -120.71,
        -120.7 , -120.69, -120.68, -120.67, -120.66, -120.65, -120.64,
        -120.63, -120.62, -120.61, -120.6 , -120.59, -120.58, -120.57,
        -120.56, -120.55, -120.54, -120.53, -120.52, -120.51, -120.5 ,
        -120.49, -120.48, -120.47, -120.46, -120.45, -120.44, -120.43,
        -120.42, -120.41, -120.4 , -120.39, -120.38, -120.37, -120.36,
        -120.35, -120.34, -120.33, -120.32, -120.31, -120.3 , -120.29,
        -120.28, -120.27, -120.26, -120.25, -120.24, -120.23, -120.22,
        -120.21, -120.2 , -120.19, -120.18, -120.17, -120.16, -120.15,
        -120.14, -120.13, -120.12, -120.11, -120.1 , -120.09, -120.08,
        -120.07, -120.06, -120.05, -120.04, -120.03, -120.02, -120.01,
        -120.  , -119.99, -119.98, -119.97, -119.96, -119.95, -119.94,
        -119.93, -119.92, -119.91, -119.9 , -119.89, -119.88, -119.87,
        -119.86, -119.85, -119.84, -119.83, -119.82, -119.81, -119.8 ,
        -119.79, -119.78, -119.77, -119.76, -119.75, -119.74, -119.73,
        -119.72, -119.71, -119.7 , -119.69, -119.68, -119.67, -119.66,
        -119.65, -119.64, -119.63, -119.62, -119.61, -119.6 , -119.59,
        -119.58, -119.57, -119.56, -119.55, -119.54, -119.53, -119.52,
        -119.51, -119.5 , -119.49, -119.48, -119.47, -119.46, -119.45,
        -119.44, -119.43, -119.42, -119.41, -119.4 , -119.39, -119.38,
        -119.37, -119.36, -119.35, -119.34, -119.33, -119.32, -119.31,
        -119.3 , -119.29, -119.28, -119.27, -119.26, -119.25, -119.24,
        -119.23, -119.22, -119.21, -119.2 , -119.19, -119.18, -119.17,
        -119.16, -119.15, -119.14, -119.13, -119.12, -119.11, -119.1 ,
        -119.09, -119.08, -119.07, -119.06, -119.05, -119.04, -119.03,
        -119.02, -119.01, -119.  , -118.99, -118.98, -118.97, -118.96,
        -118.95, -118.94, -118.93, -118.92, -118.91, -118.9 , -118.89,
        -118.88, -118.87, -118.86, -118.85, -118.84, -118.83, -118.82,
        -118.81, -118.8 , -118.79, -118.78, -118.77, -118.76, -118.75,
        -118.74, -118.73, -118.72, -118.71, -118.7 , -118.69, -118.68,
        -118.67, -118.66, -118.65, -118.64, -118.63, -118.62, -118.61,
        -118.6 , -118.59, -118.58, -118.57, -118.56, -118.55, -118.54,
        -118.53, -118.52, -118.51, -118.5 , -118.49, -118.48, -118.47,
        -118.46, -118.45, -118.44, -118.43, -118.42, -118.41, -118.4 ,
        -118.39, -118.38, -118.37, -118.36, -118.35, -118.34, -118.33,
        -118.32, -118.31, -118.3 , -118.29, -118.28, -118.27, -118.26,
        -118.25, -118.24, -118.23, -118.22, -118.21, -118.2 , -118.19,
        -118.18, -118.17, -118.16, -118.15, -118.14, -118.13, -118.12,
        -118.11, -118.1 , -118.09, -118.08, -118.07, -118.06, -118.05,
        -118.04, -118.03, -118.02, -118.01, -118.  , -117.99, -117.98,
        -117.97, -117.96, -117.95, -117.94, -117.93, -117.92, -117.91,
        -117.9 , -117.89, -117.88, -117.87, -117.86, -117.85, -117.84,
        -117.83, -117.82, -117.81, -117.8 , -117.79, -117.78, -117.77,
        -117.76, -117.75, -117.74, -117.73, -117.72, -117.71, -117.7 ,
        -117.69, -117.68, -117.67, -117.66, -117.65, -117.64, -117.63,
        -117.62, -117.61, -117.6 , -117.59, -117.58, -117.57, -117.56,
        -117.55, -117.54, -117.53, -117.52, -117.51, -117.5 , -117.49,
        -117.48, -117.47, -117.46, -117.45, -117.44, -117.43, -117.42,
        -117.41, -117.4 , -117.39, -117.38, -117.37, -117.36, -117.35,
        -117.34, -117.33, -117.32, -117.31, -117.3 , -117.29, -117.28,
        -117.27, -117.26, -117.25, -117.24, -117.23, -117.22, -117.21,
        -117.2 , -117.19, -117.18, -117.17, -117.16, -117.15, -117.14,
        -117.13, -117.12, -117.11, -117.1 , -117.09, -117.08, -117.07,
        -117.06, -117.05, -117.04, -117.03, -117.02, -117.01, -117.  ,
        -116.99, -116.98, -116.97, -116.96, -116.95, -116.94, -116.93,
        -116.92, -116.91, -116.9 , -116.89, -116.88, -116.87, -116.86,
        -116.85, -116.84, -116.83, -116.82, -116.81, -116.8 , -116.79,
        -116.78, -116.77, -116.76, -116.75, -116.74, -116.73, -116.72,
        -116.71, -116.69, -116.68, -116.67, -116.66, -116.63, -116.62,
        -116.61, -116.6 , -116.58, -116.57, -116.56, -116.55, -116.54,
        -116.53, -116.52, -116.51, -116.5 , -116.49, -116.48, -116.47,
        -116.46, -116.45, -116.44, -116.43, -116.42, -116.41, -116.4 ,
        -116.39, -116.38, -116.37, -116.36, -116.35, -116.34, -116.33,
        -116.32, -116.31, -116.3 , -116.29, -116.28, -116.26, -116.25,
        -116.24, -116.23, -116.22, -116.21, -116.2 , -116.19, -116.18,
        -116.17, -116.15, -116.14, -116.09, -116.08, -116.06, -116.05,
        -116.02, -116.01, -116.  , -115.99, -115.98, -115.96, -115.95,
        -115.94, -115.93, -115.9 , -115.85, -115.84, -115.8 , -115.75,
        -115.73, -115.72, -115.62, -115.6 , -115.59, -115.58, -115.57,
        -115.56, -115.55, -115.54, -115.53, -115.52, -115.51, -115.5 ,
        -115.49, -115.48, -115.46, -115.41, -115.4 , -115.39, -115.38,
        -115.37, -115.32, -115.22, -114.98, -114.94, -114.73, -114.68,
        -114.67, -114.66, -114.65, -114.64, -114.63, -114.6 , -114.59,
        -114.58, -114.57, -114.55, -114.49, -114.47, -114.31]),
 array([32.54, 32.55, 32.56, 32.57, 32.58, 32.59, 32.6 , 32.61, 32.62,
        32.63, 32.64, 32.65, 32.66, 32.67, 32.68, 32.69, 32.7 , 32.71,
        32.72, 32.73, 32.74, 32.75, 32.76, 32.77, 32.78, 32.79, 32.8 ,
        32.81, 32.82, 32.83, 32.84, 32.85, 32.86, 32.87, 32.88, 32.89,
        32.9 , 32.91, 32.92, 32.93, 32.94, 32.95, 32.96, 32.97, 32.98,
        32.99, 33.  , 33.01, 33.02, 33.03, 33.04, 33.05, 33.06, 33.07,
        33.08, 33.09, 33.1 , 33.11, 33.12, 33.13, 33.14, 33.15, 33.16,
        33.17, 33.18, 33.19, 33.2 , 33.21, 33.22, 33.23, 33.24, 33.25,
        33.26, 33.27, 33.28, 33.29, 33.3 , 33.31, 33.32, 33.33, 33.34,
        33.35, 33.36, 33.37, 33.38, 33.39, 33.4 , 33.41, 33.42, 33.43,
        33.44, 33.45, 33.46, 33.47, 33.48, 33.49, 33.5 , 33.51, 33.52,
        33.53, 33.54, 33.55, 33.56, 33.57, 33.58, 33.59, 33.6 , 33.61,
        33.62, 33.63, 33.64, 33.65, 33.66, 33.67, 33.68, 33.69, 33.7 ,
        33.71, 33.72, 33.73, 33.74, 33.75, 33.76, 33.77, 33.78, 33.79,
        33.8 , 33.81, 33.82, 33.83, 33.84, 33.85, 33.86, 33.87, 33.88,
        33.89, 33.9 , 33.91, 33.92, 33.93, 33.94, 33.95, 33.96, 33.97,
        33.98, 33.99, 34.  , 34.01, 34.02, 34.03, 34.04, 34.05, 34.06,
        34.07, 34.08, 34.09, 34.1 , 34.11, 34.12, 34.13, 34.14, 34.15,
        34.16, 34.17, 34.18, 34.19, 34.2 , 34.21, 34.22, 34.23, 34.24,
        34.25, 34.26, 34.27, 34.28, 34.29, 34.3 , 34.31, 34.32, 34.33,
        34.34, 34.35, 34.36, 34.37, 34.38, 34.39, 34.4 , 34.41, 34.42,
        34.43, 34.44, 34.45, 34.46, 34.47, 34.48, 34.49, 34.5 , 34.51,
        34.52, 34.53, 34.54, 34.55, 34.56, 34.57, 34.58, 34.59, 34.6 ,
        34.61, 34.62, 34.63, 34.64, 34.65, 34.66, 34.67, 34.68, 34.69,
        34.7 , 34.71, 34.72, 34.73, 34.74, 34.75, 34.77, 34.82, 34.83,
        34.85, 34.86, 34.87, 34.88, 34.89, 34.9 , 34.91, 34.92, 34.93,
        34.94, 34.95, 34.96, 34.97, 34.98, 34.99, 35.  , 35.02, 35.03,
        35.04, 35.05, 35.06, 35.08, 35.1 , 35.11, 35.12, 35.13, 35.14,
        35.15, 35.16, 35.17, 35.18, 35.19, 35.2 , 35.22, 35.23, 35.24,
        35.25, 35.26, 35.27, 35.28, 35.29, 35.3 , 35.31, 35.32, 35.33,
        35.34, 35.35, 35.36, 35.37, 35.38, 35.39, 35.4 , 35.41, 35.42,
        35.43, 35.44, 35.45, 35.46, 35.47, 35.48, 35.49, 35.5 , 35.51,
        35.52, 35.55, 35.56, 35.58, 35.59, 35.6 , 35.61, 35.62, 35.63,
        35.64, 35.65, 35.67, 35.68, 35.69, 35.7 , 35.72, 35.73, 35.74,
        35.75, 35.76, 35.78, 35.79, 35.82, 35.85, 35.86, 35.87, 35.88,
        35.89, 35.9 , 35.91, 35.94, 35.95, 35.96, 35.97, 35.99, 36.  ,
        36.01, 36.02, 36.04, 36.05, 36.06, 36.07, 36.08, 36.09, 36.1 ,
        36.11, 36.12, 36.13, 36.14, 36.15, 36.16, 36.18, 36.19, 36.2 ,
        36.21, 36.22, 36.23, 36.25, 36.27, 36.28, 36.29, 36.3 , 36.31,
        36.32, 36.33, 36.34, 36.35, 36.36, 36.37, 36.38, 36.39, 36.4 ,
        36.41, 36.42, 36.43, 36.44, 36.45, 36.47, 36.48, 36.49, 36.5 ,
        36.51, 36.52, 36.53, 36.54, 36.55, 36.56, 36.57, 36.58, 36.59,
        36.6 , 36.61, 36.62, 36.63, 36.64, 36.65, 36.66, 36.67, 36.68,
        36.69, 36.7 , 36.71, 36.72, 36.73, 36.74, 36.75, 36.76, 36.77,
        36.78, 36.79, 36.8 , 36.81, 36.82, 36.83, 36.84, 36.85, 36.86,
        36.87, 36.88, 36.89, 36.9 , 36.91, 36.92, 36.93, 36.94, 36.95,
        36.96, 36.97, 36.98, 36.99, 37.  , 37.01, 37.02, 37.03, 37.04,
        37.05, 37.06, 37.07, 37.08, 37.09, 37.1 , 37.11, 37.12, 37.13,
        37.14, 37.15, 37.16, 37.17, 37.18, 37.19, 37.2 , 37.21, 37.22,
        37.23, 37.24, 37.25, 37.26, 37.27, 37.28, 37.29, 37.3 , 37.31,
        37.32, 37.33, 37.34, 37.35, 37.36, 37.37, 37.38, 37.39, 37.4 ,
        37.41, 37.42, 37.43, 37.44, 37.45, 37.46, 37.47, 37.48, 37.49,
        37.5 , 37.51, 37.52, 37.53, 37.54, 37.55, 37.56, 37.57, 37.58,
        37.59, 37.6 , 37.61, 37.62, 37.63, 37.64, 37.65, 37.66, 37.67,
        37.68, 37.69, 37.7 , 37.71, 37.72, 37.73, 37.74, 37.75, 37.76,
        37.77, 37.78, 37.79, 37.8 , 37.81, 37.82, 37.83, 37.84, 37.85,
        37.86, 37.87, 37.88, 37.89, 37.9 , 37.91, 37.92, 37.93, 37.94,
        37.95, 37.96, 37.97, 37.98, 37.99, 38.  , 38.01, 38.02, 38.03,
        38.04, 38.05, 38.06, 38.07, 38.09, 38.1 , 38.11, 38.12, 38.13,
        38.14, 38.15, 38.16, 38.17, 38.18, 38.19, 38.2 , 38.21, 38.22,
        38.23, 38.24, 38.25, 38.26, 38.27, 38.28, 38.29, 38.3 , 38.31,
        38.32, 38.33, 38.34, 38.35, 38.36, 38.37, 38.38, 38.39, 38.4 ,
        38.41, 38.42, 38.43, 38.44, 38.45, 38.46, 38.47, 38.48, 38.49,
        38.5 , 38.51, 38.52, 38.53, 38.54, 38.55, 38.56, 38.57, 38.58,
        38.59, 38.6 , 38.61, 38.62, 38.63, 38.64, 38.65, 38.66, 38.67,
        38.68, 38.69, 38.7 , 38.71, 38.72, 38.73, 38.74, 38.75, 38.76,
        38.77, 38.78, 38.79, 38.8 , 38.81, 38.82, 38.83, 38.84, 38.85,
        38.86, 38.87, 38.89, 38.9 , 38.91, 38.92, 38.93, 38.94, 38.95,
        38.96, 38.97, 38.98, 38.99, 39.  , 39.01, 39.02, 39.03, 39.04,
        39.05, 39.06, 39.07, 39.08, 39.09, 39.1 , 39.11, 39.12, 39.13,
        39.14, 39.15, 39.16, 39.17, 39.18, 39.19, 39.2 , 39.21, 39.22,
        39.23, 39.24, 39.25, 39.26, 39.27, 39.28, 39.29, 39.3 , 39.31,
        39.32, 39.33, 39.34, 39.35, 39.36, 39.37, 39.38, 39.39, 39.4 ,
        39.41, 39.42, 39.43, 39.44, 39.45, 39.46, 39.47, 39.48, 39.49,
        39.5 , 39.51, 39.52, 39.53, 39.54, 39.55, 39.56, 39.59, 39.64,
        39.65, 39.66, 39.67, 39.68, 39.69, 39.7 , 39.71, 39.72, 39.73,
        39.74, 39.75, 39.76, 39.77, 39.78, 39.79, 39.8 , 39.81, 39.82,
        39.83, 39.86, 39.88, 39.9 , 39.92, 39.93, 39.94, 39.95, 39.97,
        40.01, 40.02, 40.03, 40.05, 40.06, 40.07, 40.08, 40.09, 40.11,
        40.12, 40.13, 40.14, 40.15, 40.16, 40.17, 40.18, 40.19, 40.2 ,
        40.22, 40.23, 40.24, 40.25, 40.26, 40.27, 40.28, 40.29, 40.3 ,
        40.31, 40.32, 40.34, 40.35, 40.37, 40.38, 40.39, 40.4 , 40.41,
        40.42, 40.43, 40.44, 40.45, 40.46, 40.47, 40.48, 40.49, 40.5 ,
        40.51, 40.52, 40.53, 40.54, 40.55, 40.56, 40.57, 40.58, 40.59,
        40.6 , 40.61, 40.62, 40.63, 40.64, 40.65, 40.66, 40.67, 40.68,
        40.69, 40.71, 40.72, 40.73, 40.74, 40.75, 40.76, 40.77, 40.78,
        40.79, 40.8 , 40.81, 40.82, 40.85, 40.86, 40.87, 40.88, 40.89,
        40.91, 40.92, 40.93, 40.94, 40.95, 40.97, 40.98, 40.99, 41.01,
        41.02, 41.04, 41.07, 41.09, 41.11, 41.12, 41.13, 41.15, 41.2 ,
        41.21, 41.23, 41.26, 41.28, 41.3 , 41.31, 41.32, 41.35, 41.36,
        41.38, 41.4 , 41.41, 41.43, 41.46, 41.48, 41.5 , 41.54, 41.6 ,
        41.61, 41.63, 41.66, 41.69, 41.7 , 41.72, 41.73, 41.74, 41.75,
        41.76, 41.77, 41.78, 41.79, 41.8 , 41.81, 41.84, 41.86, 41.88,
        41.92, 41.95]),
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
        40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.]),
 array([6.0000e+00, 1.5000e+01, 1.6000e+01, ..., 3.2054e+04, 3.7937e+04,
        3.9320e+04]),
 array([2.000e+00, 3.000e+00, 4.000e+00, ..., 5.290e+03, 5.471e+03,
        6.210e+03]),
 array([3.0000e+00, 8.0000e+00, 9.0000e+00, ..., 1.6122e+04, 1.6305e+04,
        3.5682e+04]),
 array([2.000e+00, 3.000e+00, 4.000e+00, ..., 5.050e+03, 5.189e+03,
        5.358e+03]),
 array([ 0.4999,  0.536 ,  0.5495, ..., 14.5833, 15.    , 15.0001]),
 array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [29]:
housing_cat = pd.DataFrame(housing_cat,columns=housing.columns,index=housing.index)

In [30]:
housing_cat

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
12655,239.0,569.0,28.0,3555.0,795.0,2167.0,704.0,1815.0,1.0
15502,662.0,55.0,6.0,4411.0,853.0,1965.0,766.0,9519.0,4.0
2908,481.0,273.0,43.0,1410.0,308.0,625.0,298.0,3475.0,1.0
14053,672.0,21.0,23.0,1669.0,517.0,856.0,481.0,1959.0,4.0
20496,515.0,174.0,26.0,3269.0,644.0,1791.0,578.0,6883.0,0.0
...,...,...,...,...,...,...,...,...,...
15174,678.0,49.0,13.0,4852.0,1208.0,1976.0,996.0,7805.0,0.0
12661,243.0,568.0,14.0,5072.0,1354.0,3353.0,1322.0,3341.0,1.0
19263,113.0,561.0,47.0,518.0,164.0,416.0,170.0,4239.0,0.0
19140,115.0,548.0,13.0,2924.0,578.0,1166.0,499.0,6403.0,0.0
19773,171.0,701.0,26.0,877.0,220.0,583.0,195.0,4107.0,1.0

# 3. One -Hot Encoder

In [31]:
housing = housing[['ocean_proximity']]
housing

      ocean_proximity
12655          INLAND
15502      NEAR OCEAN
2908           INLAND
14053      NEAR OCEAN
20496       <1H OCEAN
...               ...
15174       <1H OCEAN
12661          INLAND
19263       <1H OCEAN
19140       <1H OCEAN
19773          INLAND

[16512 rows x 1 columns]

In [32]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
one_hot_encoder = OneHotEncoder()

In [34]:
one_hot_encoder

OneHotEncoder()

In [35]:
hausing_cat = one_hot_encoder.fit_transform(housing)

In [36]:
hausing_cat.toarray()

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [37]:
housing_cat_data = pd.DataFrame(hausing_cat.toarray(), columns=['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
                                index=housing.index)

In [38]:
housing_cat_data

       <1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
12655        0.0     1.0     0.0       0.0         0.0
15502        0.0     0.0     0.0       0.0         1.0
2908         0.0     1.0     0.0       0.0         0.0
14053        0.0     0.0     0.0       0.0         1.0
20496        1.0     0.0     0.0       0.0         0.0
...          ...     ...     ...       ...         ...
15174        1.0     0.0     0.0       0.0         0.0
12661        0.0     1.0     0.0       0.0         0.0
19263        1.0     0.0     0.0       0.0         0.0
19140        1.0     0.0     0.0       0.0         0.0
19773        0.0     1.0     0.0       0.0         0.0

[16512 rows x 5 columns]

In [39]:
# concat this data indo real datasets
df = pd.concat([df,housing_cat_data],axis=1)

In [40]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-122.23,37.88,41,880,129.0,322,126,8.3252,452600,NEAR BAY,0.0,0.0,0.0,1.0,0.0
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,358500,NEAR BAY,0.0,0.0,0.0,1.0,0.0
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,352100,NEAR BAY,0.0,0.0,0.0,1.0,0.0
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,341300,NEAR BAY,0.0,0.0,0.0,1.0,0.0
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,342200,NEAR BAY,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,78100,INLAND,0.0,1.0,0.0,0.0,0.0
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,77100,INLAND,0.0,1.0,0.0,0.0,0.0
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,92300,INLAND,0.0,1.0,0.0,0.0,0.0
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,84700,INLAND,0.0,1.0,0.0,0.0,0.0
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,89400,INLAND,NaN,NaN,NaN,NaN,NaN

In [41]:
df = df.drop('ocean_proximity',axis=1)

In [42]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-122.23,37.88,41,880,129.0,322,126,8.3252,452600,0.0,0.0,0.0,1.0,0.0
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,358500,0.0,0.0,0.0,1.0,0.0
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,352100,0.0,0.0,0.0,1.0,0.0
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,341300,0.0,0.0,0.0,1.0,0.0
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,342200,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,78100,0.0,1.0,0.0,0.0,0.0
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,77100,0.0,1.0,0.0,0.0,0.0
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,92300,0.0,1.0,0.0,0.0,0.0
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,84700,0.0,1.0,0.0,0.0,0.0
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,89400,NaN,NaN,NaN,NaN,NaN

# Feature Scalling  method => 1 se

In [57]:
# load dataframe 
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-122.23,37.88,41,880,129.0,322,126,8.3252,452600,0.0,0.0,0.0,1.0,0.0
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,358500,0.0,0.0,0.0,1.0,0.0
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,352100,0.0,0.0,0.0,1.0,0.0
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,341300,0.0,0.0,0.0,1.0,0.0
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,342200,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,78100,0.0,1.0,0.0,0.0,0.0
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,77100,0.0,1.0,0.0,0.0,0.0
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,92300,0.0,1.0,0.0,0.0,0.0
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,84700,0.0,1.0,0.0,0.0,0.0
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,89400,NaN,NaN,NaN,NaN,NaN

In [58]:
# Sklearn se 
from sklearn.preprocessing import MinMaxScaler

In [59]:
scaler = MinMaxScaler(feature_range=(-1,1))
scaler

MinMaxScaler(feature_range=(-1, 1))

In [60]:
scaled_value = scaler.fit_transform(df)

In [61]:
scaled_value

array([[-0.57768924,  0.13496281,  0.56862745, ..., -1.        ,
         1.        , -1.        ],
       [-0.57569721,  0.13071201, -0.21568627, ..., -1.        ,
         1.        , -1.        ],
       [-0.57968127,  0.12858661,  1.        , ..., -1.        ,
         1.        , -1.        ],
       ...,
       [-0.37649402,  0.46439957, -0.37254902, ..., -1.        ,
        -1.        , -1.        ],
       [-0.39641434,  0.46439957, -0.33333333, ..., -1.        ,
        -1.        , -1.        ],
       [-0.38047809,  0.45164718, -0.41176471, ...,         nan,
                nan,         nan]])

In [62]:
# Convert Array into dataFrame 
df_scaled = pd.DataFrame(scaled_value,columns=df.columns,index=df.index)

In [63]:
df_scaled

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-0.577689,0.134963,0.568627,-0.955339,-0.960273,-0.982118,-0.958888,0.079337,0.804533,-1.0,-1.0,-1.0,1.0,-1.0
1,-0.575697,0.130712,-0.215686,-0.638995,-0.657045,-0.865579,-0.626048,0.076054,0.416493,-1.0,-1.0,-1.0,1.0,-1.0
2,-0.579681,0.128587,1.000000,-0.925479,-0.941341,-0.972365,-0.942115,-0.067944,0.390101,-1.0,-1.0,-1.0,1.0,-1.0
3,-0.581673,0.128587,1.000000,-0.935297,-0.927374,-0.968889,-0.928301,-0.290603,0.345566,-1.0,-1.0,-1.0,1.0,-1.0
4,-0.581673,0.128587,1.000000,-0.917341,-0.913408,-0.968497,-0.915146,-0.538448,0.349277,-1.0,-1.0,-1.0,1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-0.350598,0.475027,-0.058824,-0.915408,-0.884233,-0.952801,-0.891794,-0.853740,-0.739791,-1.0,1.0,-1.0,-1.0,-1.0
20636,-0.374502,0.477152,-0.333333,-0.964647,-0.953755,-0.980212,-0.962835,-0.716294,-0.743914,-1.0,1.0,-1.0,-1.0,-1.0
20637,-0.376494,0.464400,-0.372549,-0.885447,-0.849783,-0.943720,-0.857918,-0.834471,-0.681234,-1.0,1.0,-1.0,-1.0,-1.0
20638,-0.396414,0.464400,-0.333333,-0.905489,-0.873371,-0.958631,-0.885545,-0.811409,-0.712574,-1.0,1.0,-1.0,-1.0,-1.0
20639,-0.380478,0.451647,-0.411765,-0.858436,-0.809125,-0.922419,-0.826015,-0.739493,-0.693193,NaN,NaN,NaN,NaN,NaN

# Feature sacaling Method => 2

In [67]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-122.23,37.88,41,880,129.0,322,126,8.3252,452600,0.0,0.0,0.0,1.0,0.0
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,358500,0.0,0.0,0.0,1.0,0.0
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,352100,0.0,0.0,0.0,1.0,0.0
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,341300,0.0,0.0,0.0,1.0,0.0
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,342200,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,78100,0.0,1.0,0.0,0.0,0.0
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,77100,0.0,1.0,0.0,0.0,0.0
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,92300,0.0,1.0,0.0,0.0,0.0
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,84700,0.0,1.0,0.0,0.0,0.0
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,89400,NaN,NaN,NaN,NaN,NaN

In [64]:
from sklearn.preprocessing import StandardScaler

In [65]:
stander_scale = StandardScaler()

In [66]:
stander_scale

StandardScaler()

In [68]:
stander_scale_values = stander_scale.fit_transform(df)

In [69]:
stander_scale_values

array([[-1.32783522,  1.05254828,  0.98214266, ..., -0.0110063 ,
         2.81778327, -0.38421741],
       [-1.32284391,  1.04318455, -0.60701891, ..., -0.0110063 ,
         2.81778327, -0.38421741],
       [-1.33282653,  1.03850269,  1.85618152, ..., -0.0110063 ,
         2.81778327, -0.38421741],
       ...,
       [-0.8237132 ,  1.77823747, -0.92485123, ..., -0.0110063 ,
        -0.3548889 , -0.38421741],
       [-0.87362627,  1.77823747, -0.84539315, ..., -0.0110063 ,
        -0.3548889 , -0.38421741],
       [-0.83369581,  1.75014627, -1.00430931, ...,         nan,
                nan,         nan]])

In [70]:
stander_scale_values_in_dataFrame = pd.DataFrame(stander_scale_values,columns=df.columns,index=df.index)

In [71]:
stander_scale_values_in_dataFrame

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-1.327835,1.052548,0.982143,-0.804819,-0.970325,-0.974429,-0.977033,2.344766,2.129631,-0.887683,-0.68391,-0.011006,2.817783,-0.384217
1,-1.322844,1.043185,-0.607019,2.045890,1.348276,0.861439,1.669961,2.332238,1.314156,-0.887683,-0.68391,-0.011006,2.817783,-0.384217
2,-1.332827,1.038503,1.856182,-0.535746,-0.825561,-0.820777,-0.843637,1.782699,1.258693,-0.887683,-0.68391,-0.011006,2.817783,-0.384217
3,-1.337818,1.038503,1.856182,-0.624215,-0.718768,-0.766028,-0.733781,0.932968,1.165100,-0.887683,-0.68391,-0.011006,2.817783,-0.384217
4,-1.337818,1.038503,1.856182,-0.462404,-0.611974,-0.759847,-0.629157,-0.012881,1.172900,-0.887683,-0.68391,-0.011006,2.817783,-0.384217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-0.758826,1.801647,-0.289187,-0.444985,-0.388895,-0.512592,-0.443449,-1.216128,-1.115804,-0.887683,1.46218,-0.011006,-0.354889,-0.384217
20636,-0.818722,1.806329,-0.845393,-0.888704,-0.920488,-0.944405,-1.008420,-0.691593,-1.124470,-0.887683,1.46218,-0.011006,-0.354889,-0.384217
20637,-0.823713,1.778237,-0.924851,-0.174995,-0.125472,-0.369537,-0.174042,-1.142593,-0.992746,-0.887683,1.46218,-0.011006,-0.354889,-0.384217
20638,-0.873626,1.778237,-0.845393,-0.355600,-0.305834,-0.604429,-0.393753,-1.054583,-1.058608,-0.887683,1.46218,-0.011006,-0.354889,-0.384217
20639,-0.833696,1.750146,-1.004309,0.068408,0.185416,-0.033977,0.079672,-0.780129,-1.017878,NaN,NaN,NaN,NaN,NaN